"""add accounts, transaction direction status notes, budget currency

Revision ID: 191268db951a
Revises: 7b3b00be8476
Create Date: 2026-08-26 01:06:48.984234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '191268db951a'
down_revision: Union[str, None] = '7b3b00be8476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_budget_category_period'), type_='unique')
        batch_op.create_unique_constraint('uq_budget_category_period_currency', ['category_id', 'period', 'currency'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('INCOME', 'EXPENSE', 'SAVINGS', 'TRANSFER', name='categorytype'),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.Enum('INFLOW', 'OUTFLOW', name='transactiondirection'), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('FINALIZED', 'PENDING', name='transactionstatus'), nullable=False))
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_account_id_accounts', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_account_id_accounts', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))
        batch_op.drop_column('notes')
        batch_op.drop_column('account_id')
        batch_op.drop_column('status')
        batch_op.drop_column('direction')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('INCOME', 'EXPENSE', 'SAVINGS', 'TRANSFER', name='categorytype'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint('uq_budget_category_period_currency', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_budget_category_period'), ['category_id', 'period'])
        batch_op.drop_column('currency')

    op.drop_table('accounts')
    # ### end Alembic commands ###
