"""add budget defaults

Revision ID: 81ff66dbfbd9
Revises: 191268db951a
Create Date: 2026-08-26 05:49:30.215432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ff66dbfbd9'
down_revision: Union[str, None] = '191268db951a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('planned_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'currency', name='uq_budget_default_category_currency')
    )
    with op.batch_alter_table('budget_defaults', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_defaults_category_id'), ['category_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_defaults', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_defaults_category_id'))

    op.drop_table('budget_defaults')
    # ### end Alembic commands ###
